package com.example.util

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val shortLabel: String) {
    FA("fa", "فارسی", "فا"),
    EN("en", "English", "EN")
}

data class AppStrings(
    // App & Header
    val appTitle: String,
    val selectTv: String,
    val tapToConnectWifi: String,
    val toggleTvMonitor: String,
    val connectionGuide: String,
    val powerButton: String,
    val languageToggle: String,
    val liteModeOn: String,
    val liteModeOff: String,
    val liteModeTooltip: String,
    val connectedTo: String,
    val disconnected: String,
    val connectionFailed: String,

    // Navigation Tabs
    val tabRemote: String,
    val tabGamepad: String,
    val tabMouse: String,
    val tabKeyboard: String,
    val tabApps: String,
    val tabFiles: String,
    val tabTools: String,

    // Gamepad Screen
    val gamepadTitle: String,
    val gamepadSubtitle: String,
    val dpadMode: String,
    val joystickMode: String,
    val controlModeLabel: String,
    val turboMode: String,
    val turboModeDesc: String,
    val actionButtons: String,
    val shoulderTriggers: String,
    val selectBtn: String,
    val startBtn: String,
    val fullscreenGamepad: String,
    val exitFullscreen: String,

    // Remote Screen
    val assistant: String,
    val inputSource: String,
    val settings: String,
    val up: String,
    val down: String,
    val left: String,
    val right: String,
    val ok: String,
    val back: String,
    val home: String,
    val menu: String,
    val volumeAndMedia: String,
    val volumeUp: String,
    val volumeDown: String,
    val mute: String,
    val rewind: String,
    val playPause: String,
    val fastForward: String,

    // Mouse Screen
    val mouseTitle: String,
    val mouseDragHelper: String,
    val mouseClickHelper: String,
    val scrollStrip: String,
    val scrollUp: String,
    val scrollDown: String,
    val leftClick: String,
    val rightClick: String,
    val mouseSensitivity: String,
    val liteModeActiveNotice: String,

    // Keyboard Screen
    val keyboardTitle: String,
    val keyboardSubtitle: String,
    val keyboardPlaceholder: String,
    val clear: String,
    val sendToTv: String,
    val pasteClipboard: String,
    val spaceKey: String,
    val backspaceKey: String,
    val enterKey: String,
    val quickPhrases: String,
    val textSent: String,
    val clipboardSent: String,

    // Apps Screen
    val appsTitle: String,
    val appsSubtitle: String,
    val searchAppsPlaceholder: String,
    val noAppsFound: String,
    val launchApp: String,
    val forceStopApp: String,
    val appDetails: String,
    val launchingApp: String,
    val appStopped: String,

    // Files Screen
    val storageTitle: String,
    val storageFreePrefix: String,
    val storageFreeSuffix: String,
    val storageUnitBytes: String,
    val storageUnitKb: String,
    val storageUnitMb: String,
    val storageUnitGb: String,
    val folderLabel: String,
    val newFolder: String,
    val newFolderDialogTitle: String,
    val enterFolderName: String,
    val create: String,
    val cancel: String,
    val uploadFile: String,
    val uploadDialogTitle: String,
    val uploadVideo: String,
    val uploadMusic: String,
    val uploadApk: String,
    val uploadDocument: String,
    val playOnTv: String,
    val deleteItem: String,
    val emptyFolder: String,
    val parentFolder: String,
    val folderCreated: String,
    val fileDeleted: String,
    val fileUploaded: String,
    val playingOnTv: String,
    val filesNotConnectedTitle: String,
    val filesNotConnectedDesc: String,
    val connectToTv: String,

    // Tools Screen
    val toolsTitle: String,
    val toolsSubtitle: String,
    val webUrlTitle: String,
    val sendUrl: String,
    val screenshotTitle: String,
    val screenshotSubtitle: String,
    val sleepTimerTitle: String,
    val sleepTimerSubtitle: String,
    val setTimer15m: String,
    val setTimer30m: String,
    val setTimer60m: String,
    val timerSetNotice: String,
    val adbTerminalTitle: String,
    val adbTerminalSubtitle: String,
    val quickCommandsTitle: String,
    val cmdStorage: String,
    val cmdReboot: String,
    val cmdWifi: String,
    val cmdCache: String,
    val terminalPlaceholder: String,
    val execute: String,
    val connectionSpecsTitle: String,
    val tvModelLabel: String,
    val lanIpLabel: String,
    val connectionTypeLabel: String,
    val p2pDirectDescription: String,

    // Device Picker Sheet
    val deviceSheetTitle: String,
    val deviceSheetSubtitle: String,
    val scanAgain: String,
    val detectedDevices: String,
    val scanningWifi: String,
    val manualIpButton: String,
    val setupGuideButton: String,
    val manualDialogTitle: String,
    val manualNameLabel: String,
    val manualIpLabel: String,
    val manualPortLabel: String,
    val directConnect: String,
    val noDevicesFound: String,
    val savedDevicesSection: String,

    // Setup Help Dialog
    val helpDialogTitle: String,
    val helpDialogDescription: String,
    val helpStep1: String,
    val helpStep2: String,
    val helpStep3: String,
    val helpStep4: String,
    val helpStep5: String,
    val helpDismissButton: String
) {
    // Convenient aliases for UI screens
    val paste: String get() = pasteClipboard
    val space: String get() = spaceKey
    val backspace: String get() = backspaceKey
    val enter: String get() = enterKey
    val searchSuggestions: String get() = quickPhrases
    val keyboardControlKeys: String get() = if (clear == "پاک کردن") "کلیدهای کنترلی کیبورد:" else "Control Keys:"
    val installedApps: String get() = appsTitle
    val installedAppsSubtitle: String get() = appsSubtitle
    val launchOnTv: String get() = launchApp
    val forceStop: String get() = forceStopApp
    val internalStorage: String get() = storageTitle
    val storageFree: String get() = storageFreePrefix
    val sendFilesToTv: String get() = uploadFile
    val createNewFolderTitle: String get() = newFolderDialogTitle
    val folderNamePlaceholder: String get() = enterFolderName
    val sendApk: String get() = uploadApk
    val sendVideo: String get() = uploadVideo
    val sendAudio: String get() = uploadMusic
    val selectFileTypeToSend: String get() = if (clear == "پاک کردن") "نوع فایلی که می‌خواهید به تلویزیون منتقل شود را انتخاب کنید:" else "Select the type of file you want to transfer to the TV:"
    val delete: String get() = deleteItem
    val openUrlInTv: String get() = webUrlTitle
    val send: String get() = sendUrl
    val tvScreenshot: String get() = screenshotTitle
    val captureInstant: String get() = screenshotSubtitle
    val sleepTimer: String get() = sleepTimerTitle
    val mins: String get() = if (clear == "پاک کردن") "د" else "m"
    val adbShellTitle: String get() = adbTerminalTitle
    val adbDirectPort: String get() = if (clear == "پاک کردن") "پورت مستقیم ۵۵۵۵" else "Direct Port 5555"
    val commandPlaceholder: String get() = terminalPlaceholder
    val lanConnectionDetails: String get() = connectionSpecsTitle
    val tvModel: String get() = tvModelLabel
    val lanIpAddress: String get() = lanIpLabel
    val connectionType: String get() = connectionTypeLabel
    val p2pDirect: String get() = p2pDirectDescription
    val close: String get() = if (clear == "پاک کردن") "بستن" else "Close"
    val urlPlaceholder: String get() = "https://..."
}

val PersianStrings = AppStrings(
    appTitle = "کنترل هوشمند گوگل تی‌وی",
    selectTv = "انتخاب تلویزیون...",
    tapToConnectWifi = "لمس برای اتصال به وای‌فای",
    toggleTvMonitor = "نمایش/مخفی مانیتور تلویزیون",
    connectionGuide = "راهنمای اتصال",
    powerButton = "خاموش/روشن",
    languageToggle = "English",
    liteModeOn = "عملکرد بهینه: روشن",
    liteModeOff = "عملکرد بهینه: خاموش",
    liteModeTooltip = "بهینه‌سازی برای گوشی‌های ضعیف",
    connectedTo = "متصل شد به",
    disconnected = "اتصال قطع شد",
    connectionFailed = "خطا در اتصال به",

    tabRemote = "ریموت",
    tabGamepad = "دسته بازی",
    tabMouse = "ماوس",
    tabKeyboard = "کیبورد",
    tabApps = "برنامه‌ها",
    tabFiles = "فایل‌ها",
    tabTools = "ابزارها",

    gamepadTitle = "دسته بازی هوشمند تلویزیون",
    gamepadSubtitle = "کنترل بازی‌های گوگل تی‌وی و شبیه‌سازها با بازخورد لرزشی و بدون تاخیر",
    dpadMode = "کلیدهای فلش ۴ جهته (D-Pad)",
    joystickMode = "جویستیک ۳۶۰ درجه (Joystick)",
    controlModeLabel = "حالت کنترل حرکت:",
    turboMode = "حالت توربو (شلیک رگباری)",
    turboModeDesc = "ارسال سریع و پشت سر هم کلید با نگه داشتن دکمه",
    actionButtons = "کلیدهای اکشن",
    shoulderTriggers = "کلیدهای شانه (L/R)",
    selectBtn = "SELECT",
    startBtn = "START",
    fullscreenGamepad = "تمام‌صفحه گیم‌پد",
    exitFullscreen = "خروج از تمام‌صفحه",

    assistant = "دستیار",
    inputSource = "ورودی",
    settings = "تنظیمات",
    up = "بالا",
    down = "پایین",
    left = "چپ",
    right = "راست",
    ok = "OK",
    back = "بازگشت",
    home = "خانه",
    menu = "منو",
    volumeAndMedia = "کنترل صدا و مدیا",
    volumeUp = "صدا +",
    volumeDown = "صدا -",
    mute = "بی‌صدا",
    rewind = "عقب",
    playPause = "پخش/توقف",
    fastForward = "جلو",

    mouseTitle = "تاچ‌پد ماوس زنده تلویزیون",
    mouseDragHelper = "برای حرکت ماوس انگشت خود را بکشید",
    mouseClickHelper = "یک لمس: کلیک چپ | لمس طولانی: کلیک راست",
    scrollStrip = "اسکرول",
    scrollUp = "اسکرول بالا",
    scrollDown = "اسکرول پایین",
    leftClick = "کلیک چپ (انتخاب)",
    rightClick = "کلیک راست (منو)",
    mouseSensitivity = "حساسیت ماوس:",
    liteModeActiveNotice = "حالت روان برای گوشی‌های ضعیف فعال است",

    keyboardTitle = "کیبورد هوشمند تلویزیون",
    keyboardSubtitle = "تایپ مستقیم متن، جستجو و ارسال لینک بدون نیاز به ریموت دستی",
    keyboardPlaceholder = "متن، لینک یا جستجوی مورد نظر را اینجا بنویسید...",
    clear = "پاک کردن",
    sendToTv = "ارسال به تلویزیون",
    pasteClipboard = "الصاق از کلیپ‌بورد",
    spaceKey = "فاصله (Space)",
    backspaceKey = "حذف",
    enterKey = "اینتر",
    quickPhrases = "کلمات و عبارات پرکاربرد",
    textSent = "متن به تلویزیون ارسال شد",
    clipboardSent = "از کلیپ‌بورد به تلویزیون ارسال شد",

    appsTitle = "برنامه‌های نصب‌شده روی تلویزیون",
    appsSubtitle = "مشاهده و اجرای مستقیم اپلیکیشن‌های گوگل تی‌وی با یک لمس",
    searchAppsPlaceholder = "جستجوی برنامه در تلویزیون...",
    noAppsFound = "هیچ برنامه‌ای یافت نشد",
    launchApp = "اجرای برنامه",
    forceStopApp = "توقف اجباری",
    appDetails = "جزئیات برنامه",
    launchingApp = "در حال اجرای",
    appStopped = "متوقف شد",

    storageTitle = "حافظه داخلی گوگل تی‌وی (/sdcard)",
    storageFreePrefix = "۲۵.۶ گیگابایت آزاد از ۶۴ گیگابایت",
    storageFreeSuffix = "آزاد",
    storageUnitBytes = "بایت",
    storageUnitKb = "کیلوبایت",
    storageUnitMb = "مگابایت",
    storageUnitGb = "گیگابایت",
    folderLabel = "پوشه",
    newFolder = "پوشه جدید",
    newFolderDialogTitle = "ایجاد پوشه جدید در تلویزیون",
    enterFolderName = "نام پوشه را وارد کنید...",
    create = "ایجاد",
    cancel = "انصراف",
    uploadFile = "ارسال فایل",
    uploadDialogTitle = "ارسال نمونه فایل به حافظه تلویزیون",
    uploadVideo = "ارسال ویدیو (MP4)",
    uploadMusic = "ارسال آهنگ (MP3)",
    uploadApk = "ارسال فایل نصبی (APK)",
    uploadDocument = "ارسال سند (PDF)",
    playOnTv = "پخش در تلویزیون",
    deleteItem = "حذف فایل",
    emptyFolder = "این پوشه خالی است",
    parentFolder = "پوشه قبلی",
    folderCreated = "پوشه با موفقیت ایجاد شد",
    fileDeleted = "حذف شد",
    fileUploaded = "فایل با موفقیت به تلویزیون ارسال شد",
    playingOnTv = "در حال پخش روی تلویزیون",
    filesNotConnectedTitle = "تلویزیون متصل نیست",
    filesNotConnectedDesc = "جهت مشاهده فایل‌ها، ویدیوها و مدیریت حافظه تلویزیون، ابتدا تلویزیون خود را از بالای صفحه یا دکمه زیر متصل کنید.",
    connectToTv = "اتصال به تلویزیون",

    toolsTitle = "جعبه‌ابزار پیشرفته تلویزیون",
    toolsSubtitle = "ارسال لینک اینترنتی، اسکرین‌شات، تایمر خواب و ترمینال ADB شل",
    webUrlTitle = "باز کردن مستقیم آدرس اینترنتی (Web URL) در تلویزیون",
    sendUrl = "ارسال",
    screenshotTitle = "اسکرین‌شات از TV",
    screenshotSubtitle = "ثبت آنی تصویر صفحه",
    sleepTimerTitle = "تایمر خاموشی",
    sleepTimerSubtitle = "تنظیم خاموش شدن خودکار",
    setTimer15m = "۱۵ دقیقه",
    setTimer30m = "۳۰ دقیقه",
    setTimer60m = "۶۰ دقیقه",
    timerSetNotice = "تایمر خاموشی تلویزیون برای %d دقیقه تنظیم شد",
    adbTerminalTitle = "ترمینال دستورات ADB و شل",
    adbTerminalSubtitle = "ارسال مستقیم فرامین لینوکسی به تلویزیون بدون نیاز به کامپیوتر",
    quickCommandsTitle = "دستورات سریع:",
    cmdStorage = "وضعیت حافظه (df -h)",
    cmdReboot = "ریبوت تلویزیون",
    cmdWifi = "ریست وای‌فای",
    cmdCache = "پاکسازی کش",
    terminalPlaceholder = "مثال: input keyevent 3",
    execute = "اجرا",
    connectionSpecsTitle = "مشخصات ارتباط شبکه محلی:",
    tvModelLabel = "مدل تلویزیون:",
    lanIpLabel = "آدرس آی‌پی (LAN IP):",
    connectionTypeLabel = "نوع ارتباط:",
    p2pDirectDescription = "مستقیم P2P (بدون سرور واسط اینترنتی)",

    deviceSheetTitle = "جستجو و اتصال به گوگل تی‌وی",
    deviceSheetSubtitle = "اتصال خودکار وای‌فای در شبکه محلی بدون نیاز به سرور اینترنتی",
    scanAgain = "اسکن مجدد شبکه",
    detectedDevices = "تلویزیون‌های شناسایی‌شده در شبکه",
    scanningWifi = "در حال اسکن شبکه وای‌فای...",
    manualIpButton = "اتصال دستی با IP",
    setupGuideButton = "راهنمای فعال‌سازی",
    manualDialogTitle = "اتصال دستی به تلویزیون",
    manualNameLabel = "نام تلویزیون (اختیاری)",
    manualIpLabel = "آدرس IP تلویزیون",
    manualPortLabel = "پورت (پیش‌فرض ۵۵۵۵)",
    directConnect = "اتصال مستقیم",
    noDevicesFound = "هیچ تلویزیونی به صورت خودکار یافت نشد. با دکمه اتصال دستی می‌توانید IP تلویزیون را وارد کنید.",
    savedDevicesSection = "تلویزیون‌های ذخیره‌شده",

    helpDialogTitle = "راهنمای فعال‌سازی اتصال مستقیم تلویزیون",
    helpDialogDescription = "برای کنترل کامل موس، کیبورد، برنامه‌ها و فایل‌ها، قابلیت عیب‌یابی شبکه را روی گوگل تی‌وی فعال کنید:",
    helpStep1 = "به تنظیمات تلویزیون (Settings) و سپس بخش System > About بروید.",
    helpStep2 = "روی گزینه Android TV OS build هفت (۷) بار ممتد کلیک کنید تا پیام You are now a developer ظاهر شود.",
    helpStep3 = "به عقب برگشته و وارد منوی جدید Developer options شوید.",
    helpStep4 = "گزینه Network debugging یا Wireless debugging را روشن (ON) کنید.",
    helpStep5 = "گوشی و تلویزیون هر دو به یک شبکه وای‌فای متصل باشند؛ تلویزیون فوراً شناسایی می‌شود!",
    helpDismissButton = "متوجه شدم"
)

val EnglishStrings = AppStrings(
    appTitle = "Google TV Remote",
    selectTv = "Select TV...",
    tapToConnectWifi = "Tap to connect via Wi-Fi",
    toggleTvMonitor = "Show/Hide TV Monitor",
    connectionGuide = "Connection Guide",
    powerButton = "Power On/Off",
    languageToggle = "فارسی",
    liteModeOn = "Lite Mode: ON",
    liteModeOff = "Lite Mode: OFF",
    liteModeTooltip = "Optimize for low-end phones",
    connectedTo = "Connected to",
    disconnected = "Disconnected",
    connectionFailed = "Failed to connect to",

    tabRemote = "Remote",
    tabGamepad = "Gamepad",
    tabMouse = "Mouse",
    tabKeyboard = "Keyboard",
    tabApps = "Apps",
    tabFiles = "Files",
    tabTools = "Tools",

    gamepadTitle = "Smart TV Gamepad",
    gamepadSubtitle = "Play Android TV games and emulators with ultra-low latency & haptics",
    dpadMode = "4-Way D-Pad",
    joystickMode = "360° Joystick",
    controlModeLabel = "Movement Mode:",
    turboMode = "Turbo Rapid-Fire",
    turboModeDesc = "Continuous keypress when holding action buttons",
    actionButtons = "Action Buttons",
    shoulderTriggers = "Shoulders (L/R)",
    selectBtn = "SELECT",
    startBtn = "START",
    fullscreenGamepad = "Fullscreen Gamepad",
    exitFullscreen = "Exit Fullscreen",

    assistant = "Assistant",
    inputSource = "Input",
    settings = "Settings",
    up = "Up",
    down = "Down",
    left = "Left",
    right = "Right",
    ok = "OK",
    back = "Back",
    home = "Home",
    menu = "Menu",
    volumeAndMedia = "Volume & Media Controls",
    volumeUp = "Vol +",
    volumeDown = "Vol -",
    mute = "Mute",
    rewind = "Rewind",
    playPause = "Play/Pause",
    fastForward = "Fast Forward",

    mouseTitle = "Live Google TV Trackpad",
    mouseDragHelper = "Drag finger to move mouse pointer",
    mouseClickHelper = "Single tap: Left click | Long press: Right click",
    scrollStrip = "Scroll",
    scrollUp = "Scroll Up",
    scrollDown = "Scroll Down",
    leftClick = "Left Click (Select)",
    rightClick = "Right Click (Menu)",
    mouseSensitivity = "Mouse Sensitivity:",
    liteModeActiveNotice = "Smooth Lite Mode active for low-end devices",

    keyboardTitle = "Smart TV Keyboard",
    keyboardSubtitle = "Direct text typing, search & URLs without clumsy remote navigation",
    keyboardPlaceholder = "Type text, search query or URL here...",
    clear = "Clear",
    sendToTv = "Send to TV",
    pasteClipboard = "Paste Clipboard",
    spaceKey = "Space",
    backspaceKey = "Delete",
    enterKey = "Enter",
    quickPhrases = "Quick Search Shortcuts",
    textSent = "Text sent to TV",
    clipboardSent = "Clipboard sent to TV",

    appsTitle = "Installed Apps on TV",
    appsSubtitle = "Browse and launch Google TV applications with a single tap",
    searchAppsPlaceholder = "Search apps on TV...",
    noAppsFound = "No apps found",
    launchApp = "Launch App",
    forceStopApp = "Force Stop",
    appDetails = "App Details",
    launchingApp = "Launching",
    appStopped = "Stopped",

    storageTitle = "Google TV Internal Storage (/sdcard)",
    storageFreePrefix = "25.6 GB free of 64 GB",
    storageFreeSuffix = "free",
    storageUnitBytes = "bytes",
    storageUnitKb = "KB",
    storageUnitMb = "MB",
    storageUnitGb = "GB",
    folderLabel = "Folder",
    newFolder = "New Folder",
    newFolderDialogTitle = "Create New Folder on TV",
    enterFolderName = "Enter folder name...",
    create = "Create",
    cancel = "Cancel",
    uploadFile = "Upload File",
    uploadDialogTitle = "Upload Sample File to TV Storage",
    uploadVideo = "Upload Video (MP4)",
    uploadMusic = "Upload Music (MP3)",
    uploadApk = "Upload App Package (APK)",
    uploadDocument = "Upload Document (PDF)",
    playOnTv = "Play on TV",
    deleteItem = "Delete File",
    emptyFolder = "This folder is empty",
    parentFolder = "Parent Folder",
    folderCreated = "Folder created successfully",
    fileDeleted = "Deleted",
    fileUploaded = "File sent to TV successfully",
    playingOnTv = "Playing on TV",
    filesNotConnectedTitle = "TV Not Connected",
    filesNotConnectedDesc = "To view files, browse storage, or play media, connect to your TV using the top header or the button below.",
    connectToTv = "Connect to TV",

    toolsTitle = "Advanced TV Toolbox",
    toolsSubtitle = "Send Web URLs, take screenshots, sleep timer, and ADB Shell terminal",
    webUrlTitle = "Open Web URL directly in TV Browser",
    sendUrl = "Send",
    screenshotTitle = "TV Screenshot",
    screenshotSubtitle = "Instant screen capture",
    sleepTimerTitle = "Sleep Timer",
    sleepTimerSubtitle = "Set auto power off",
    setTimer15m = "15 min",
    setTimer30m = "30 min",
    setTimer60m = "60 min",
    timerSetNotice = "TV sleep timer set for %d minutes",
    adbTerminalTitle = "ADB Shell & Linux Terminal",
    adbTerminalSubtitle = "Send raw shell commands directly to TV without a computer",
    quickCommandsTitle = "Quick Commands:",
    cmdStorage = "Storage (df -h)",
    cmdReboot = "Reboot TV",
    cmdWifi = "Reset Wi-Fi",
    cmdCache = "Clear Cache",
    terminalPlaceholder = "Example: input keyevent 3",
    execute = "Run",
    connectionSpecsTitle = "Local Network Specs:",
    tvModelLabel = "TV Model:",
    lanIpLabel = "LAN IP Address:",
    connectionTypeLabel = "Connection Type:",
    p2pDirectDescription = "Direct P2P (No intermediary cloud server)",

    deviceSheetTitle = "Search & Connect to Google TV",
    deviceSheetSubtitle = "Automatic Wi-Fi discovery on local network without cloud server",
    scanAgain = "Scan Wi-Fi Again",
    detectedDevices = "Discovered TVs on Local Network",
    scanningWifi = "Scanning local Wi-Fi network...",
    manualIpButton = "Connect via Manual IP",
    setupGuideButton = "Setup Guide",
    manualDialogTitle = "Manual TV Connection",
    manualNameLabel = "TV Name (Optional)",
    manualIpLabel = "TV IP Address",
    manualPortLabel = "Port (Default: 5555)",
    directConnect = "Direct Connect",
    noDevicesFound = "No TVs detected automatically. You can use 'Connect via Manual IP' to enter your TV's IP address.",
    savedDevicesSection = "Saved Devices",

    helpDialogTitle = "Google TV Direct Connection Setup Guide",
    helpDialogDescription = "To enable full mouse, keyboard, app launcher and file management, turn on Network Debugging on your Google TV:",
    helpStep1 = "Go to TV Settings > System > About.",
    helpStep2 = "Click 'Android TV OS build' 7 times rapidly until 'You are now a developer' appears.",
    helpStep3 = "Go back one level and open the new 'Developer options' menu.",
    helpStep4 = "Toggle 'Network debugging' or 'Wireless debugging' to ON.",
    helpStep5 = "Ensure your phone and TV are on the same Wi-Fi; TV will be discovered immediately!",
    helpDismissButton = "Got It"
)

val LocalAppStrings = compositionLocalOf { PersianStrings }
val LocalAppLanguage = compositionLocalOf { AppLanguage.FA }
val LocalLiteMode = compositionLocalOf { false }
